/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.CardLayout;
//import model.Address;
import model.person;
import model.PersonDirectory;
import ui.PersonDetails.PersondetailsworkareaJPanel;
/**
 *
 * @author manasvini
 */
public class MainJFrame extends javax.swing.JFrame {
     private PersonDirectory persondirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.persondirectory=new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        TopPanel = new javax.swing.JPanel();
        btndetails = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        TopPanel.setBackground(new java.awt.Color(204, 204, 255));

        btndetails.setBackground(new java.awt.Color(102, 102, 255));
        btndetails.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btndetails.setText("Person Details");
        btndetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btndetails, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(btndetails)
                .addGap(36, 36, 36))
        );

        SplitPane.setTopComponent(TopPanel);

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        SplitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetailsActionPerformed
        // TODO add your handling code here:
        PersondetailsworkareaJPanel panel = new  PersondetailsworkareaJPanel(userProcessContainer,persondirectory);
        userProcessContainer.add("PersondetailsworkareaJPanel", panel);//adding this panel to container
        
        //adding in userprocessorcontainer for switching view
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btndetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton btndetails;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        
        
        
        person newPerson =persondirectory.addperson();
        newPerson.setFirstName("Rachel");
        newPerson.setLastName("Green");
        newPerson.setAge(21);
        newPerson.setGender('F');
        newPerson.setSSN("784672343");
        newPerson.getWorkAddress().setState("MA"); 
        newPerson.getHomeAddress().setPhonenumber("9837765763");
        newPerson.getWorkAddress().setPhonenumber("1234567890");
        newPerson.getHomeAddress().setState("MA");
        newPerson.getWorkAddress().setStreetAddress("123 tremont st");
        newPerson.getWorkAddress().setZipcode(23456L);
        newPerson.getWorkAddress().setCity("Boston");
        newPerson.getHomeAddress().setCity("Boston");
        newPerson.getHomeAddress().setStreetAddress("103 Huntington Ave");
        newPerson.getHomeAddress().setZipcode(21340L);
        newPerson.getHomeAddress().setUnitNumber("988");
        newPerson.getWorkAddress().setUnitNumber("110");
        
        person newPerson1 =persondirectory.addperson();
        newPerson1.setFirstName("Manu");
        newPerson1.setLastName("Kottapally");
        newPerson1.setAge(22);
        newPerson1.setGender('F');
        newPerson1.setSSN("784623456");
        newPerson1.getWorkAddress().setState("MA"); 
        newPerson1.getHomeAddress().setPhonenumber("9837761234");
        newPerson1.getWorkAddress().setPhonenumber("1234512345");
        newPerson1.getHomeAddress().setState("MA");
        newPerson1.getWorkAddress().setStreetAddress("16 Bird st");
        newPerson1.getWorkAddress().setZipcode(12345L);
        newPerson1.getWorkAddress().setCity("Boston");
        newPerson1.getHomeAddress().setCity("Boston");
        newPerson1.getHomeAddress().setStreetAddress("360 Huntington Ave");
        newPerson1.getHomeAddress().setZipcode(12309L);
        newPerson1.getHomeAddress().setUnitNumber("777");
        newPerson1.getWorkAddress().setUnitNumber("123");
        
        
    }
}
